### PR TITLE
added missing autotools files

### PR DESCRIPTION
**Pull request by pfasante**
adds the files requested for in https://github.com/dstehle/fplll/issues/11

### CODE REVIEW

**Comment by malb** [comment]
I think this is bad practice as it will create tons and tons of merge conflicts and will only produce frustration. If you want an easier way for people to get started, you shoul write an ./autogen.sh bash script which runs autoreconf -i and creates the m4 directory.

**Comment by pfasante** [comment]
ok, I agree with that, did not had it in mind. Perhaps there should be a note in the readme about autoreconf then?

**Comment by malb** [comment]
Yep, that'd be good. In fact, someone (hint hint) should convert the README to markdown so it's displayed on github appropriately and update it to explain how to build the library when checking out of git.

**Comment by pfasante** [comment]
Good, I'll take a look at it

**Pull request closed without merging**
